#!/usr/bin/env bash
# Configures a new Ubuntu machine

sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo mv index.nginx-debian.html /var/www/html/index.nginx-debian.html

sudo service nginx restart
