#!/usr/bin/env bash
# Install and configures a new Ubuntu machine

sudo apt-get update

sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i "s/root \/var\/www\/html;/root \/var\/www\/html;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com;\n\t}/" /etc/nginx/sites-available/default

sudo service nginx restart
