#!/usr/bin/env bash
# Install and configures a new Ubuntu machine

sudo apt-get update

sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i "s/server_name _;/server_name _;\n\n\trewrite ^\/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com;\n\t}/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i "s/listen 80 default_server;/listen 80 default_server;\n\n\terror_page 404 \/404.html;\n\tlocation \/404.html {\n\t\tinternal;\n\t}/" /etc/nginx/sites-enabled/default

sudo service nginx status
sudo service nginx restart
