#!/usr/bin/env bash
# Script that installs and configures HAproxy in a load balancer 

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get -y install haproxy=2.8.\*

echo -e "\nfrontend web-frontend\n\tbind *:80\n\tmode http\n\tstats uri /haproxy?stats\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 105584-web-01 18.210.20.176 check\n\tserver 105584-web-02 105584-web-02 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
