#!/usr/bin/env bash
# Script that installs and configures HAproxy in a load balancer 

sudo apt-get -y install s--no-install-recommend software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get -y update
sudo apt-get -y install haproxy=2.7.\*

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo -e "\nfrontend web-frontend\n\tbind *:80\n\tmode http\n\tstats uri /haproxy?stats\n\tdefault_backend web-backend\n\nbackend web-backend\n\tmode http\n\tbalance roundrobin\n\tserver 105584-web-01 18.210.20.176:80 check\n\tserver 105584-web-02 54.89.28.110:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
