#!/usr/bin/env bash
#  5-is_the_host_on_the_network: Pings an IP address passed as an argument.
#+ Accepts a string as an argument
#+ Display Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if
#+ no argument is passed

if [ "$#" -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
