#!/usr/bin/env bash
# 100-process_and_pid_file:
#+ Creates the file '/var/run/myscript.pid' containing its PID
#+ Displays 'To infinity and beyond' indefinitely
#+ Displays 'I hate the kill command' when receiving a SIGTERM signal
#+ Displays 'Y U no love me?!' when receiving a SIGNINT signal
#+ Deletes the file 'var/run/myscript.pid' and terminates itself when
#+ receiving a SIGQUIT or SIGTERM signal

echo $$ >> /var/run/myscript.pid

valid="true"

while [ "$valid" ]
do
echo "To infinity and beyond"
sleep 2
trap "echo I hate the kill command; rm -rf /var/run/myscript.pid; exit" 15
trap "echo Y U no love me?!" 2
trap "rm -rf /var/run/myscript.pid; exit" 3
done
