#!/usr/bin/env bash
# 5-dont_stop_me_now: Stops 4-to_infinity_and_beyond process.
# shellcheck disable=SC2009

process_pid=$(ps a | grep ./4-to_infinity_and_beyond | head -n 1 | cut -f2 -d " ")
kill -9 "${process_pid}"
