#!/usr/bin/env bash
#  4-if_9_say_hi: Displays "Best School" 10 times,
#+ but for the 9th iteration, displays Best School and then Hi on a new line.

valid="true"
counter=1

while [ $valid ]
do
echo "Best School"
if [ $counter -eq 9 ]
then
echo "Hi"
fi
if [ $counter -eq 10 ]
then
break
fi
((counter++))
done
