#!/usr/bin/env bash
# 5-4_bad_luck_8_is_your_chance: loops from 1 to 10

valid="true"
counter=1

while [ $valid ]
do
if [ $counter -eq 4 ]
then
echo "bad luck"
elif [ $counter -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
if [ $counter -eq 10 ]
then
break
fi
((counter++))
done
