#!/usr/bin/env bash
# 6-superstitious_numbers: loops from 1 to 20

valid="true"
counter=1

while [ $valid ]
do
case $counter in
4)
echo "$counter"
echo "bad luck from China" ;;
9)
echo "$counter"
echo "bad luck from Japan" ;;
17)
echo "$counter"
echo "bad luck from Italy" ;;
*)
echo "$counter"
esac
if [ $counter -eq 20 ]
then
break
fi
((counter++))
done
