#!/usr/bin/env bash
#  7-clock: Displays the time for 12 hours and 59 minutes:
#+ display hours from 0 to 12
#+ display minutes from 1 to 59

valid="true"
min=0
hours=0

while [ $valid ]
do
	((remainder = min % 60))
	if [ $remainder -eq 0 ]
	then
		((hours++))
		echo "Hour: $hours"
		min=1
	else
		echo "$min"
		((min++))
	fi
	if [[ ( $hours -eq 12 && $min -eq 59 ) ]]
	then
		echo "$min"
		break
	fi
done
