#!/usr/bin/env bash
#  0-change_your_home_IP: Configures an Ubuntu server with the below requirements:
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i '0,/127\.0\.0\.1/{s//127\.0\.0\.2/}' ~/hosts.new
cp -f ~/hosts.new ~/ht.bk
sed -i '0,/localhost/{s/localhost/&\n8\.8\.8\.8        facebook\.com/}' ~/ht.bk
cat ~/ht.bk > /etc/hosts
rm -f ~/ht.bk ~/hosts.new
