#!/usr/bin/env bash
# Configure server to run nginx as user nginx listening on port 8080.

sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default

chmod 644 /etc/nginx/nginx.conf

sudo -u nginx service nginx start
